version: '3.9'

services:
  db:
    image: postgres:15.1
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
  api:
    build: ./src/api
    environment:
      - API_PORT=${API_PORT}
    ports:
      - '${API_PORT}:${API_PORT}'
    command: npm start
  web:
    build: ./src/web
    ports:
      - '8080:8080'
    command: npm start
