export const SET_HEADER_TAB_BEGIN = 'SET_HEADER_TAB_BEGIN';
export const SET_HEADER_TAB_SUCCESS = 'SET_HEADER_TAB_SUCCESS';
export const SET_HEADER_TAB_FAILURE = 'SET_HEADER_TAB_FAILURE';
export const SET_TITLE = 'SET_TITLE';
